Admin:
  AvailableCommands: # Commands available to admins
    - LogConfig
    - Freeze
    - Alert
    - Xray
    - Evaluate
    - Note
    - Warn
    - Mute
    - SMute
    - Kick
    - TempBan
    - Ban
    - Unban
    - Strip
    - ClearChat
    - RestrictChat
    - OpenChat
    - Spy
    - Track
    - Vanish
    - Toggle
    - InvSee
    - CycleTeleport
    - Chat
    - Aimbot
    - Register
  PermissionMessage: '&4&l[&c&o&lADMIN&r&4&l] &cOnly admins can use this command'
  
Mod:
  AvailableCommands: # Commands available to mods
    - Freeze
    - Alert
    - Xray
    - Evaluate
    - Note
    - Warn
    - Mute
    - SMute
    - Kick
    - Ban
    - TempBan
    - Unban
    - Strip
    - ClearChat
    - Spy
    - Track
    - Vanish
    - Toggle
    - InvSee
    - CycleTeleport
    - Chat
    - Aimbot
  PermissionMessage: '&l&4[&cMOD&4]&r &cOnly mods can use this command'

Helper:
  AvailableCommands: # Commands available to helpers
    - Alert
    - Freeze
    - Note
    - Warn
    - Mute
    - SMute
    - Kick
    - Strip
    - ClearChat
    - Spy
    - Track
    - Vanish
    - Toggle
    - InvSee
    - CycleTeleport
    - Chat
  PermissionMessage: '&l&4[&cHELPER&4]&r &cOnly helpers can use this command'

Report:
  ConfigNote: 'Sender: {admin} Target: {player} Reason {message}'

Freeze:
  ConfigNote: 'Sender: {admin} Target: {player} Reason: {message}'

Alert:
  HelperTag:
    - '&5&l[&dHELPER&5&l] &r&c{message}'
  ModTag:
    - '&4&l[&c&lMOD&4&l] &r&c&l{message}'
  AdminTag:
    - '&4&l[&c&o&lADMIN&r&4&l] &r&c&l{message}'
  ConfigNote: 'Sender: {admin} Message: {message}'

Xray:
  ConfigNote: 'Sender: {admin} Target: {player}'

Evaluate: # [s] = Player Stats
  Player: # [r] = Player Reports 
    - '[s]UUID'
    - '[s]REPORT'
    - '[r]REPORT'
    - '[s]NOTE'
    - '[s]WARN'
    - '[s]STRIP'
    - '[s]FREEZE'
    - '[s]XRAY'
    - '[s]MUTE'
    - '[s]SMUTE'
    - '[s]KICK'
    - '[s]TEMPBAN'
    - '[s]BAN'
    - '[s]UNBAN'
  Staff:
    - '[s]UUID'
    - '[s]REPORT'
    - '[r]REPORT'
    - '[s]NOTE'
    - '[s]WARN'
    - '[s]STRIP'
    - '[s]FREEZE'
    - '[s]XRAY'
    - '[s]MUTE'
    - '[s]SMUTE'
    - '[s]KICK'
    - '[s]TEMPBAN'
    - '[s]BAN'
    - '[s]UNBAN'
    - '[r]FREEZE'
    - '[r]ALERT'
    - '[r]XRAY'
    - '[r]EVALUATE'
    - '[r]NOTE'
    - '[r]WARN'
    - '[r]MUTE'
    - '[r]SMUTE'
    - '[r]KICK'
    - '[r]TEMPBAN'
    - '[r]BAN'
    - '[r]UNBAN'
    - '[r]STRIP'
    - '[r]CLEARCHAT'
    - '[r]RESTRICTCHAT'
    - '[r]SPY'
    - '[r]INVSEE'
  ConfigNote: 'Sender: {admin} Target: {player}'

Warn:
  ConfigNote: 'Sender: {admin} Target: {player} Reason: {message}'

Mute:
  ConfigNote: 'Sender: {admin} Target: {player} Reason: {message}'

SMute:
  Config Note: 'Sender: {admin} Target: {player} Reason: {message}'

Kick:
  NoJoinMessage:
    - '&8&l--- &4&lLudum Network &8&l---'
    - ''
    - '&c&l{player}&r&7, you have been kicked'
    - '&7&oKicked By: &4{admin}'
    - ''
    - '&6&lReason:'
    - '&e{message}'
    - ''
    - '&8&l---&4&l<:>&8&l---'
  ConfigNote: 'Sender: {admin} Target: {player} Reason: {message}'

TempBan:
  NoJoinMessage:
    - '&8&l--- &4&lLudum Network &8&l---'
    - ''
    - '&c&l{player}&r&7, you have been temp-banned'
    - '&7&oBanned By: &4{admin}'
    - ''
    - '&7Unban in: &4&l{time}'
    - ''
    - '&6&lReason:'
    - '&e{message}'
    - ''
    - '&8&l---&4&l<:>&8&l---'
  ConfigNote: 'Sender: {admin} Target: {player} Reason: {message}'
  
Ban:
  NoJoinMessage:
    - '&8&l--- &4&lLudum Network &8&l---'
    - ''
    - '&c&l{player}&r&7, you have been banned'
    - '&7&oBanned By: &4{admin}'
    - ''
    - '&7Unban in: &4&lPERMANENT'
    - ''
    - '&6&lReason:'
    - '&e{message}'
    - ''
    - '&8&l---&4&l<:>&8&l---'
  GlobalTag:
    - '&4&l[&c&o&lBAN&r&4&l] &c&l{player} &r&chas been banned by &l{admin}'
    - '&4&l[&c&o&lBAN&r&4&l] &r&c&lReason: &r&7{message}'
  ConfigNote: 'Sender: {admin} Target: {player} Reason: {message}'

Unban:
  ConfigNote: 'Sender: {admin} Target: {player} Reason: {message}'

Strip:
  ConfigNote: 'Sender: {admin} Target: {player}'
  
ClearChat:
  GlobalTag:
    - '&7&l[&eCHAT&7&l] &6&l{admin} &fhas cleared the chat'
    - '&7&l[&eCHAT&7&l] &fReason: &7{message}'
  ConfigNote: 'Sender: {admin} Reason: {message}'

RestrictChat:
  GlobalTag:
    - '&7&l[&eCHAT&7&l] &6&l{admin} &fhas restricted the chat'
    - '&7&l[&eCHAT&7&l] &fReason: &7{message}'
  ConfigNote: 'Sender: {admin} Reason: {message}'

OpenChat:
  GlobalTag:
    - '&7&l[&eCHAT&7&l] &6&l{admin} &fhas opened the chat'

Spy:
  ConfigNote: 'Sender: {admin} Target: {player} Reason: {message}'

InvSee:
  ConfigNote: 'Sender: {admin} Target: {player}'

GUI: # Graphical User Interface
  Freeze:
    Name: '&l&bFREEZE'
    ItemID: 79
    Slot: 5
  Alert:
    Name: '&l&5ALERT'
    ItemID: 95
    Slot: 9
  Xray:
    Name: '&l&8XRAY'
    ItemID: 56
    Slot: 8
  Evaluate:
    Name: '&l&3EVALUATE'
    ItemID: 47
    Slot: 14
  Note:
    Name: '&l&2NOTE'
    ItemID: 63
    Slot: 10
  Warn:
    Name: '&l&4WARN'
    ItemID: 175
    Slot: 19
  Mute:
    Name: '&l&3MUTE'
    ItemID: 25
    Slot: 12
  SMute:
    Name: '&l&3SILENT MUTE'
    ItemID: 31
    Slot: 21
  Kick:
    Name: '&l&cKICK'
    ItemID: 33
    Slot: 28
  TempBan:
    Name: '&l&4TEMP BAN'
    ItemID: 34
    Slot: 11
  Ban:
    Name: '&l&o&4PERMA BAN'
    ItemID: 327
    Slot: 20
  UnBan:
    Name: '&l&2Pardon'
    ItemID: 326
    Slot: 29
  Strip:
    Name: '&l&cSTRIP'
    ItemID: 334
    Slot: 6
  ClearChat:
    Name: '&l&aCLEAR CHAT'
    ItemID: 337
    Slot: 13
  RestrictChat:
    Name: '&l&3RESTRICT CHAT'
    ItemID: 331
    Slot: 22
  OpenChat:
    Name: '&l&2OPEN CHAT'
    ItemID: 341
    Slot: 31
  Spy:
    Name: '&l&5SPY'
    ItemID: 329
    Slot: 4
  Track:
    Name: '&l&9TRACK'
    ItemID: 345
    Slot: 3
  Vanish:
    Name: '&l&7VANISH'
    ItemID: 166
    Slot: 0
  Toggle:
    Name: '&l&1TOGGLE'
    ItemID: 76
    Slot: 35
  InvSee:
    Name: '&l&9INVENTORY SEE'
    ItemID: 130
    Slot: 2
  CycleTeleport:
    Name: '&l&6CYCLE TELEPORT'
    ItemID: 368
    Slot: 1
  Chat:
    Name: '&l&5STAFF CHAT'
    ItemID: 207
    Slot: 18